### ISSUE TITLE
As a intermediate user, I want to update the stock of a specific product in warehouses

### ISSUE THREAD

**Issue by Criss-Wang** [AY2021S1-CS2103-W14-4/tp#10]
... so that I can keep track of the changes in the stocks of the warehouses

**Comment by jeffreytjs** [comment]
Updated to the following issues:
Issue #88 - As a standard user, I want to add details of warehouses and stocks for each product
Issue #94 - As an intermediate user, I want to update the stock of a specific product in warehouses
