### ISSUE TITLE
As a potential user, I want to have all the relevant contact details, store and retrieve stocks numbers I want displayed and highlighted quickly

### ISSUE THREAD

**Issue by Criss-Wang** [AY2021S1-CS2103-W14-4/tp#12]
... so that I can find the most important information without spending time looking through a long list of contacts.

**Comment by jeffreytjs** [comment]
This user story is satisfied by both [`view`](https://github.com/AY2021S1-CS2103-W14-4/tp/blob/master/docs/UserGuide.md#viewing-a-specific-supplier-view) and [`find`](https://github.com/AY2021S1-CS2103-W14-4/tp/blob/master/docs/UserGuide.md#finding-relevant-suppliers-find) commands.

Where `find` is able to filter for suppliers/warehouses of interest and `view` is able to quickly access the details of a particular supplier/warehouse.
