### ISSUE TITLE
Names, addresses and emails accepting / as an input

### ISSUE THREAD

**Issue by tohyuting** [AY2021S1-CS2103-W14-4/tp#135]
This might cause some issues when users use a wrong prefix, it will be captured as the name. Also, if wrong prefix is used after an input that requires number as input, a wrong exception will be thrown ("Integer provided is not zero based") instead of warning user that a wrong type of prefix has been used.

**Comment by jeffreytjs** [comment]
In my PR I have addressed validation for names, addresses and remarks. Do we want to validate emails as well?
