### ISSUE TITLE
Create basic UML diagrams

### ISSUE THREAD

**Issue by zhengweii** [AY2021S1-CS2103-W14-4/tp#70]
These UML diagrams will help to provide us with a high-level overview of the interactions between the different components

**Comment by jeffreytjs** [comment]
UML Diagram can be accessed via this link to [diagram.net stored on gdrive](https://drive.google.com/file/d/1ck801fYu1gRLEnS8Zzj9a15q9VrTm0Re/view?usp=sharing)
