### ISSUE TITLE
As a standard user, I want to view the information of a specific warehouse or supplier

### ISSUE THREAD

**Issue by Criss-Wang** [AY2021S1-CS2103-W14-4/tp#9]
... so that I can retrieve details about suppliers/warehouses I can’t remember and contact them.

**Comment by jeffreytjs** [comment]
Updated to the following issues:
Issue #93 - As I standard user, I want to view the information of a specific warehouse or supplier

**Comment by jeffreytjs** [comment]
Closing deprecated issue.
